// One entry per service page. Plain English first, the technical term second.
export type ServicePage = {
  slug: string; name: string; art: "scan" | "fix" | "write" | "links" | "map" | "chat";
  metaTitle: string; description: string; h1: string; h1Mark: string; lede: string;
  quickQ: string; quickA: string;
  signs: string[];
  doTitle: string; doItems: [string, string][];
  get: string[];
  ai: string[]; human: string[];
  steps: [string, string][];
  honest: string;
  faqs: { q: string; a: string }[];
  related: string[]; guide: { href: string; label: string };
};

export const servicePages: ServicePage[] = [
  {
    slug: "ai-seo-audit", name: "AI SEO Audit", art: "scan",
    metaTitle: "AI SEO Audit: Every Page Checked, Explained Simply",
    description: "An AI SEO audit checks every page of your website for what stops it ranking on Google and in AI answers. You get a plain-English fix list, reviewed by a person.",
    h1: "AI SEO audit: find out what is", h1Mark: "holding your website back",
    lede: "We check every page of your website, not a sample, and tell you in plain English what to fix first and why.",
    quickQ: "What is an AI SEO audit?",
    quickA: "An AI SEO audit is a full health check of a website that uses AI to read every page and a person to judge what matters. It finds the problems that stop a site from ranking on Google and from being quoted by AI tools like ChatGPT, such as broken links, missing page titles, slow pages, thin content, and pages Google cannot read. The result is a short, prioritized list of fixes.",
    signs: ["Your website gets few or no calls, forms, or sales from Google", "Traffic dropped and you do not know why", "You redesigned or moved your website recently", "You have never had your website checked", "An agency sent you a 90-page report you could not use"],
    doTitle: "What does the audit check?",
    doItems: [
      ["Can Google read your site?", "We check that every important page can be found, opened, and added to Google. Pages blocked by mistake are more common than you would think."],
      ["Page titles and descriptions", "These are the headline and summary people see in Google. We flag pages where they are missing, copied, too long, or unclear."],
      ["Broken links and errors", "Links that go nowhere, pages that show errors, and redirects that send visitors in circles."],
      ["Thin and copied content", "Pages with too little useful information, or pages that say the same thing as other pages on your site."],
      ["Speed and phone experience", "Slow pages and layouts that are hard to use on a phone. Most of your visitors are on one."],
      ["Ready for AI answers", "Whether your pages answer questions clearly enough for ChatGPT, Perplexity, and Google's AI summaries to quote them."],
    ],
    get: ["A plain-English report, sorted by what matters most", "For every problem: what it is, why it matters, and how to fix it", "A list of quick wins you can do this week", "A video call to walk through it and answer questions"],
    ai: ["Opens and reads every page", "Checks hundreds of details per page", "Groups problems that share one cause"],
    human: ["Decides what actually matters for your business", "Removes false alarms", "Explains each fix in plain words"],
    steps: [["You send us your website address", "No passwords needed to start. Google Search Console access helps if you have it."], ["We check every page", "AI does the reading. A person reviews the findings and sets the order of importance."], ["You get the report and a call", "We walk you through it. You can fix things yourself, hand them to your developer, or have us do it."]],
    honest: "An audit does not raise your rankings by itself. It tells you exactly what to fix. The improvement comes when the fixes are made, which you can do yourself or hand to us.",
    faqs: [
      { q: "How is an AI SEO audit different from a free online checker?", a: "Free checkers usually test one page and return a generic score. An AI SEO audit reads every page of your website, and a person reviews the findings to remove false alarms and put the fixes in order of business impact." },
      { q: "How long does an AI SEO audit take?", a: "It depends on the size of your website. A small business site is much quicker than an online store with thousands of products. You get a clear delivery date before we start." },
      { q: "Do I need to give you access to my website?", a: "No access is needed for the audit itself, because we check the site the same way Google does, from the outside. Access to Google Search Console is helpful but optional." },
      { q: "Can you fix the problems you find?", a: "Yes. Fixes are a separate, fixed-price piece of work, so you are never locked in. Many owners fix the quick wins themselves and hand us the technical items." },
    ],
    related: ["technical-seo", "ai-search-optimization", "local-seo"], guide: { href: "/guides/how-to-use-ai-for-seo", label: "How to use AI for SEO" },
  },
  {
    slug: "technical-seo", name: "Technical SEO Fixes", art: "fix",
    metaTitle: "Technical SEO Services: Website Fixes Done for You",
    description: "Technical SEO services that fix what hurts your rankings: errors, slow pages, broken links, redirects, and the code Google reads. WordPress and Next.js.",
    h1: "Technical SEO: we fix the problems", h1Mark: "you cannot see",
    lede: "Errors, slow pages, broken links, and missing behind-the-scenes details, repaired on your live website.",
    quickQ: "What is technical SEO?",
    quickA: "Technical SEO is the work of making a website easy for search engines to find, read, and trust. It covers things visitors rarely notice: page speed, broken links, redirects, error pages, mobile layout, security, and the hidden labels in the code that tell Google and AI tools what each page is about. When these are wrong, even great content struggles to rank.",
    signs: ["Your website is slow, especially on phones", "Pages show errors or a white screen", "You changed your domain, platform, or design and traffic fell", "Google Search Console sends you warning emails", "An audit gave you a fix list and nobody to do it"],
    doTitle: "What do we fix?",
    doItems: [
      ["Errors and broken pages", "Pages that fail to load, plugin conflicts, and white screens on WordPress. Build and display errors on Next.js."],
      ["Slow pages", "Oversized images, heavy scripts, and layout jumps. These affect the speed scores Google calls Core Web Vitals."],
      ["Broken links and redirects", "Links that lead nowhere and old addresses that should point to new ones, so you keep the value of pages you have moved."],
      ["Page labels Google reads", "Titles, descriptions, and the preferred-address tag that stops duplicate pages from competing with each other."],
      ["Structured data", "Small pieces of code, called schema, that tell Google and AI tools your business name, services, reviews, and FAQs in a format they understand."],
      ["Crawler access", "The files that tell Google and AI crawlers what they may read: robots.txt, your sitemap, and llms.txt."],
    ],
    get: ["Fixes made on your live website", "A before and after list of every change", "A backup taken before anything is touched", "A re-check afterward to confirm each fix worked"],
    ai: ["Traces each error to its cause", "Writes and tests the code changes", "Re-checks every page after the fix"],
    human: ["Decides what is safe to change", "Tests on a copy of your site first", "Approves every change before it goes live"],
    steps: [["We agree on the fix list", "From our audit or from a list you already have. You get a fixed price."], ["We fix and test", "Changes are tested first, then applied to your live site with a backup in place."], ["You get the change log", "A simple before and after list, plus a re-check to prove each fix worked."]],
    honest: "Technical fixes remove what is holding you back. They do not replace helpful content. If your pages do not answer what customers ask, fixing speed alone will not make them rank.",
    faqs: [
      { q: "Which website platforms do you work on?", a: "We work at the code level on WordPress and Next.js websites. For other platforms, such as Shopify, Wix, or Squarespace, we can still advise and fix what the platform allows." },
      { q: "Will the fixes break my website?", a: "We take a backup before any change, test changes first, and apply them in small batches so anything unexpected can be undone quickly." },
      { q: "What are Core Web Vitals?", a: "Core Web Vitals are three speed and stability measurements Google uses: how fast the main content appears, how quickly the page responds when tapped, and whether the layout jumps while loading." },
    ],
    related: ["ai-seo-audit", "ai-content-writing", "ai-search-optimization"], guide: { href: "/tools/serp-preview", label: "Free Google snippet preview" },
  },
  {
    slug: "ai-content-writing", name: "AI Content Writing", art: "write",
    metaTitle: "AI SEO Content Writing, Fact-Checked by a Person",
    description: "AI SEO content writing services: articles and web pages planned from real searches, drafted with AI, then fact-checked and edited by a person. Ready to publish.",
    h1: "AI SEO content writing that is", h1Mark: "checked by a person",
    lede: "Helpful pages and articles, planned from what your customers search for, without you writing a word.",
    quickQ: "What is AI SEO content writing?",
    quickA: "AI SEO content writing is the process of using AI to research and draft web pages and articles that are built to rank in search, then having a person check the facts, add real experience, and edit the result. AI supplies speed and structure. The person supplies accuracy and the details only your business knows. Content that skips the human step is what Google's spam rules target.",
    signs: ["Your website has few pages beyond Home, About, and Contact", "You know you should blog but never have time", "Your old posts get no visitors", "Competitors show up for questions your customers ask you every day", "You tried AI writing and it sounded generic"],
    doTitle: "What do we write?",
    doItems: [
      ["Service and product pages", "Clear pages that explain what you offer, who it is for, and what happens next. These are the pages that bring in customers."],
      ["Helpful articles", "Answers to the questions your customers type into Google, such as how much something costs or which option is best."],
      ["Comparisons and buying guides", "Honest \"this versus that\" pages. AI tools often quote these when people ask for recommendations."],
      ["Content plans and briefs", "A simple calendar of what to publish and in what order, based on real searches, not guesses."],
      ["Titles, descriptions, and FAQs", "Every page arrives with its Google headline, summary, and common questions included."],
      ["Images and publishing", "Diagrams made for the page, sized so your site stays fast, and the finished page posted to your website for you."],
    ],
    get: ["Ready-to-publish pages, not rough drafts", "Every fact checked, every source linked", "Your voice, your prices, your real examples", "Internal links to your other pages", "Posted to your website if you want"],
    ai: ["Researches what already ranks", "Builds the outline and first draft", "Writes titles, summaries, and FAQs"],
    human: ["Chooses the angle that fits your business", "Checks every fact and number", "Adds your experience and edits the voice"],
    steps: [["We learn your business", "A short call about what you sell, who buys it, and what customers always ask."], ["We plan, then write", "You approve the topic list first. Then drafts arrive in batches for your review."], ["We publish and link", "Approved pages are posted, linked to related pages, and tracked."]],
    honest: "Content takes time to work. New pages commonly need weeks to months to settle in Google, and nobody can promise a position. We can promise that every page is accurate, useful, and yours.",
    faqs: [
      { q: "Does Google penalize AI-written content?", a: "Google does not penalize content for being written with AI. Google says it rewards helpful content however it is made. It does penalize mass-produced, low-value pages, which is why a person reviews and improves everything we write." },
      { q: "Will the content sound like my business?", a: "Yes. We collect your real details, such as prices, process, service area, and the way you talk to customers, and a person edits every piece so it sounds like you and not like a robot." },
      { q: "How many articles do I need each month?", a: "It depends on your market and your competitors. One genuinely useful page a week beats ten thin ones. We recommend a pace on the call and you choose." },
      { q: "Who owns the content?", a: "You do. Once delivered and paid for, every page is yours to keep and use however you like." },
    ],
    related: ["link-building", "ai-search-optimization", "ai-seo-audit"], guide: { href: "/guides/how-to-write-seo-content-with-ai", label: "How to write SEO content with AI" },
  },
  {
    slug: "link-building", name: "Link Building and Digital PR", art: "links",
    metaTitle: "Link Building Services: Earn Mentions, No Schemes",
    description: "Link building and digital PR services that earn real mentions from relevant websites. Builds the authority Google and AI tools trust. No paid link schemes.",
    h1: "Link building that earns", h1Mark: "real mentions",
    lede: "When trusted websites mention you, Google and AI tools trust you more. We earn those mentions the honest way.",
    quickQ: "What is link building?",
    quickA: "Link building is the work of getting other websites to link to yours. Google treats a link from a trusted, relevant website as a vote of confidence, so more good links usually mean better rankings. The same mentions also shape what AI tools like ChatGPT say about a business, because those tools rely heavily on what third-party websites report.",
    signs: ["Your content is good but competitors still outrank you", "Few or no other websites mention your business", "You were offered 500 links for fifty dollars and wondered if it is safe", "AI tools recommend competitors and never you", "Other sites mention your name without linking to you"],
    doTitle: "How do we earn links?",
    doItems: [
      ["Things worth linking to", "Original data, free tools, and useful guides that give other websites a reason to reference you."],
      ["Finding the right websites", "Relevant publications, blogs, directories, and partners in your industry and your area. Quality over quantity."],
      ["Personal outreach", "Real emails to real people, written for each website. No mass mail-outs."],
      ["Claiming existing mentions", "We find places that already mention you without a link and ask them to add one."],
      ["Journalist requests", "Answering reporters who are looking for expert quotes in your field."],
      ["Local mentions", "Chambers of commerce, local news, sponsorships, and community pages that matter for nearby customers."],
    ],
    get: ["A list of target websites, agreed with you", "The linkable asset, created for you", "Outreach written and sent on your behalf", "A monthly list of every mention earned"],
    ai: ["Finds and qualifies prospect websites", "Drafts outreach for each site", "Tracks replies and new mentions"],
    human: ["Approves every target website", "Personalizes and sends the emails", "Handles the real conversations"],
    steps: [["We pick an asset", "Something genuinely useful that others will want to reference."], ["We build the prospect list", "You approve the websites before anyone is contacted."], ["We reach out and report", "You see every mention earned, with links."]],
    honest: "We do not buy links, trade links in bulk, or use private link networks. Those break Google's rules and can get a site penalized. Earned links take longer and cannot be guaranteed in number, but they last.",
    faqs: [
      { q: "Are backlinks still important in 2026?", a: "Yes. Links and mentions from trusted websites remain one of the strongest signals for Google, and they also influence which businesses AI tools mention, because those tools lean on third-party sources." },
      { q: "How many links will I get?", a: "Nobody can honestly promise a number, because other website owners decide whether to link. We commit to the work: the asset, the prospect list, and the outreach, and we report every result." },
      { q: "Is buying links safe?", a: "No. Buying links breaks Google's spam policies and can lead to a penalty that removes your site from results. We only earn links." },
    ],
    related: ["ai-content-writing", "local-seo", "ai-search-optimization"], guide: { href: "/guides/generative-engine-optimization", label: "How AI tools choose who to mention" },
  },
  {
    slug: "local-seo", name: "Local SEO", art: "map",
    metaTitle: "Local SEO Services: Show Up on Google Maps",
    description: "Local SEO services that help nearby customers find you first on Google Maps and in near-me searches. Google Business Profile, reviews, and listings.",
    h1: "Local SEO: be the business", h1Mark: "nearby customers find first",
    lede: "Show up on Google Maps and in \"near me\" searches, ahead of the competitor down the road.",
    quickQ: "What is local SEO?",
    quickA: "Local SEO is the work of helping a business show up when people nearby search for what it sells. It focuses on Google Maps, the box of three local businesses Google shows for searches like \"plumber near me\", and local search results. The main ingredients are a complete Google Business Profile, steady customer reviews, the same name, address, and phone number everywhere online, and website pages about the areas you serve.",
    signs: ["You serve customers in a town, city, or region", "Competitors appear on the map and you do not", "Your Google Business Profile is unclaimed or half-finished", "You have few reviews, or old ones", "Your address or phone number is different on different websites"],
    doTitle: "What does local SEO include?",
    doItems: [
      ["Google Business Profile", "Your free Google listing, completed properly: categories, services, hours, photos, and regular updates."],
      ["Reviews", "A simple, honest way to ask happy customers for reviews, and help replying to them. No fake reviews, ever."],
      ["Consistent listings", "Your name, address, and phone number matching on the directories and apps that matter."],
      ["Service area pages", "A useful page for each area you serve, written with real local detail, not the same page with the town name swapped."],
      ["Local business code", "Schema that tells Google and AI tools exactly where you are, when you are open, and what you do."],
      ["Local mentions", "Links from local organizations, news, and community sites."],
    ],
    get: ["A complete, optimized Google Business Profile", "A review request system you can keep using", "Listings cleaned up and matched", "Service area pages on your website", "A monthly report of calls, direction requests, and map views"],
    ai: ["Finds every listing of your business online", "Spots mismatched details", "Drafts area pages and profile updates"],
    human: ["Verifies your real business details", "Adds true local knowledge", "Handles Google verification steps with you"],
    steps: [["We check your local presence", "Your profile, your listings, your reviews, and who outranks you on the map."], ["We fix the foundations", "Profile, listings, and the local details on your website."], ["We build steadily", "Reviews, area pages, and local mentions, with a simple monthly report."]],
    honest: "Google ranks the map by relevance, distance, and how well known a business is. We can improve relevance and prominence. We cannot move your building closer to the searcher, so results vary by location.",
    faqs: [
      { q: "What is the Google map pack?", a: "The Google map pack is the box with a map and three local businesses that appears at the top of Google for local searches. Those three businesses get most of the calls." },
      { q: "Do I need a website for local SEO?", a: "A Google Business Profile can work without a website, but businesses with a clear, useful website usually rank better on the map and convert more visitors into customers." },
      { q: "Can you work with service-area businesses without a shop front?", a: "Yes. Plumbers, cleaners, and other businesses that travel to customers can hide their address and set service areas instead. We set that up correctly." },
      { q: "Do you serve my city?", a: "We work remotely with businesses across the United States. Everything happens by email and Google Meet, and local details come from you and from real research on your area." },
    ],
    related: ["ai-seo-audit", "link-building", "ai-search-optimization"], guide: { href: "/ai-seo-for-small-business", label: "AI SEO for small business" },
  },
  {
    slug: "ai-search-optimization", name: "AI Search Optimization", art: "chat",
    metaTitle: "AI Search Optimization: Get Recommended by ChatGPT",
    description: "AI search optimization (GEO) services that help ChatGPT, Perplexity, Gemini, and Google AI Overviews understand, trust, and mention your business.",
    h1: "AI search optimization: get", h1Mark: "recommended by ChatGPT",
    lede: "People now ask AI who to hire. We help those tools understand your business, trust it, and mention it by name.",
    quickQ: "What is AI search optimization?",
    quickA: "AI search optimization is the work of making a business easy for AI tools to find, understand, and recommend. It is also called generative engine optimization, or GEO. AI tools such as ChatGPT, Perplexity, Gemini, and Google's AI Overviews search the web, pull short passages from pages they trust, and build an answer. AI search optimization makes your pages the ones they pull from, and makes your brand one they recognize.",
    signs: ["You asked ChatGPT about your industry and it named your competitors", "Your Google traffic is falling even though your rankings held", "Customers tell you they found you through an AI tool, or never do", "Your brand is described differently on every website", "You already do SEO and want the next step"],
    doTitle: "What does AI search optimization include?",
    doItems: [
      ["What AI says about you today", "We test real customer questions in ChatGPT, Perplexity, Gemini, and Claude and record who gets mentioned."],
      ["Pages AI can quote", "We rewrite key pages so each section answers one question directly and makes sense on its own."],
      ["Facts with sources", "AI tools prefer statements backed by named sources. We add them and link them."],
      ["One clear brand story", "The same name, description, and facts everywhere, so AI tools learn one consistent picture of your business."],
      ["The technical setup", "Schema, an llms.txt file, and crawler settings that let AI tools read your site."],
      ["Mentions where AI looks", "AI leans on third-party sites, reviews, and communities. We help you earn honest mentions there."],
    ],
    get: ["A baseline report of your AI mentions today", "Key pages rewritten to be quotable", "Technical setup for AI crawlers", "A consistent brand description to use everywhere", "Monthly tracking of mentions and AI referral visits"],
    ai: ["Runs your test questions across AI tools", "Finds passages that are hard to quote", "Drafts clearer, answer-first rewrites"],
    human: ["Chooses the questions that match real buyers", "Verifies every fact and source", "Keeps your brand voice consistent"],
    steps: [["We measure where you stand", "A fixed list of real questions, tested across the main AI tools."], ["We fix pages and setup", "Clear answers, sourced facts, consistent brand details, and crawler access."], ["We track monthly", "Same questions, same tools, so you can see mentions change over time."]],
    honest: "AI answers change from day to day and no one controls them. AI tools also mostly quote pages that already rank in search, so this work builds on regular SEO and does not replace it.",
    faqs: [
      { q: "Is AI search optimization the same as SEO?", a: "No, but they overlap. SEO gets your pages ranked in search results. AI search optimization gets passages from those pages quoted inside AI answers and gets your brand mentioned. AI tools mostly draw from pages that already rank, so SEO comes first." },
      { q: "Can you guarantee ChatGPT will recommend my business?", a: "No. Nobody can, because AI companies control their own answers and the answers vary. We improve the things that make a mention more likely and we measure the change honestly." },
      { q: "What is llms.txt?", a: "llms.txt is a simple text file on your website that describes your business and lists your most important pages for AI systems. Support for it is still uneven, but it takes minutes to add." },
      { q: "How do you measure results?", a: "We test the same list of customer questions in the main AI tools every month and record whether you are mentioned, whether your site is linked, and how many visitors arrive from AI tools." },
    ],
    related: ["ai-content-writing", "link-building", "ai-seo-audit"], guide: { href: "/guides/generative-engine-optimization", label: "Generative engine optimization guide" },
  },
];

export const getServicePage = (slug: string) => servicePages.find((s) => s.slug === slug);
